const countries = [
                'Afghanistan',
                'Albania',
                'Algeria',
                'Andorra',
                'Angola',
                'Anguilla',
                'Antigua and Barbuda',
                'Argentina',
                'Armenia',
                'Aruba',
                'Australia',
                'Austria',
                'Azerbaijan',
                'Bahamas',
                'Bahrain',
                'Bangladesh',
                'Barbados',
                'Belarus',
                'Belgium',
                'Belize',
                'Benin',
                'Bermuda',
                'Bhutan',
                'Bolivia (Plurinational State of)',
                'Bonaire',
                'Bosnia Herzegovina',
                'Botswana',
                'Br. Virgin Isds',
                'Brazil',
                'Brunei Darussalam',
                'Bulgaria',
                'Burkina Faso',
                'Burundi',
                'Cabo Verde',
                'Cambodia',
                'Cameroon',
                'Canada',
                'Cayman Isds',
                'Central African Rep.',
                'Chad',
                'Chile',
                'China',
                'China, Hong Kong SAR',
                'China, Macao SAR',
                'Colombia',
                'Comoros',
                'Congo',
                'Cook Isds',
                'Costa Rica',
                "Côte d'Ivoire",
                'Croatia',
                'Cuba',
                'Curaçao',
                'Cyprus',
                'Czechia',
                "Dem. People's Rep. of Korea",
                'Dem. Rep. of the Congo',
                'Denmark',
                'Djibouti',
                'Dominica',
                'Dominican Rep.',
                'Ecuador',
                'Egypt',
                'El Salvador',
                'Equatorial Guinea',
                'Eritrea',
                'Estonia',
                'Eswatini',
                'Ethiopia',
                'Faroe Isds',
                'Fiji',
                'Finland',
                'France',
                'French Guiana (Overseas France)',
                'French Polynesia',
                'FS Micronesia',
                'Gabon',
                'Gambia',
                'Georgia',
                'Germany',
                'Ghana',
                'Gibraltar',
                'Greece',
                'Greenland',
                'Grenada',
                'Guadeloupe (Overseas France)',
                'Guatemala',
                'Guinea',
                'Guinea-Bissau',
                'Guyana',
                'Haiti',
                'Honduras',
                'Hungary',
                'Iceland',
                'India',
                'Indonesia',
                'Iran',
                'Iraq',
                'Ireland',
                'Israel',
                'Italy',
                'Jamaica',
                'Japan',
                'Jordan',
                'Kazakhstan',
                'Kenya',
                'Kiribati',
                'Kuwait',
                'Kyrgyzstan',
                "Lao People's Dem. Rep.",
                'Latvia',
                'Lebanon',
                'Lesotho',
                'Liberia',
                'Libya',
                'Lithuania',
                'Luxembourg',
                'Madagascar',
                'Malawi',
                'Malaysia',
                'Maldives',
                'Mali',
                'Malta',
                'Marshall Isds',
                'Martinique (Overseas France)',
                'Mauritania',
                'Mauritius',
                'Mayotte (Overseas France)',
                'Mexico',
                'Mongolia',
                'Montenegro',
                'Montserrat',
                'Morocco',
                'Mozambique',
                'Myanmar',
                'N. Mariana Isds',
                'Namibia',
                'Nauru',
                'Nepal',
                'Netherlands',
                'New Caledonia',
                'New Zealand',
                'Nicaragua',
                'Niger',
                'Nigeria',
                'Niue',
                'North Macedonia',
                'Norway',
                'Oman',
                'Pakistan',
                'Palau',
                'Panama',
                'Papua New Guinea',
                'Paraguay',
                'Peru',
                'Philippines',
                'Poland',
                'Portugal',
                'Qatar',
                'Rep. of Korea',
                'Rep. of Moldova',
                'Réunion (Overseas France)',
                'Romania',
                'Russian Federation',
                'Rwanda',
                'Saint Barthélemy',
                'Saint Helena',
                'Saint Kitts and Nevis',
                'Saint Lucia',
                'Saint Maarten',
                'Saint Pierre and Miquelon',
                'Saint Vincent and the Grenadines',
                'Samoa',
                'San Marino',
                'Sao Tome and Principe',
                'Saudi Arabia',
                'Senegal',
                'Serbia',
                'Seychelles',
                'Sierra Leone',
                'Singapore',
                'Slovakia',
                'Slovenia',
                'Solomon Isds',
                'Somalia',
                'South Africa',
                'South Sudan',
                'Spain',
                'Sri Lanka',
                'State of Palestine',
                'Sudan',
                'Suriname',
                'Sweden',
                'Switzerland',
                'Syria',
                'Tajikistan',
                'Thailand',
                'Timor-Leste',
                'Togo',
                'Tokelau',
                'Tonga',
                'Trinidad and Tobago',
                'Tunisia',
                'Türkiye',
                'Turkmenistan',
                'Turks and Caicos Isds',
                'Tuvalu',
                'Uganda',
                'Ukraine',
                'United Arab Emirates',
                'United Kingdom',
                'United Rep. of Tanzania',
                'Uruguay',
                'USA',
                'Uzbekistan',
                'Vanuatu',
                'Venezuela',
                'Viet Nam',
                'Wallis and Futuna Isds',
                'Yemen',
                'Zambia',
                'Zimbabwe'
                ];